### ISSUE TITLE
http://www.makehealth.in not loading posts

### ISSUE THREAD

**Issue by luisherranz** [worona/worona-app#6]

**Comment by Poliuk** [comment]
Same problem with **viveragora.com.br**

https://app.worona.org/?siteId=Sdy8qBWCfXsYMNCF8&preview=true

```
uncaught at r TypeError: Cannot read property 'name' of undefined
    at k (https://cdn.worona.io/packages/dist/starter-app-theme-worona/app/prod/js/starter-app-theme-worona.6cfa15704b54fca458147df53b3d9309.js:11:28772)
    at s._constructComponentWithoutOwner (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:15284)
    at s._constructComponent (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:15138)
    at s.mountComponent (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:14303)
    at Object.mountComponent (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:24:1050)
    at s.performInitialMount (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:16093)
    at s.mountComponent (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:14979)
    at Object.mountComponent (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:24:1050)
    at s.performInitialMount (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:16093)
    at s.mountComponent (https://cdn.worona.io/packages/dist/vendors-app-worona/app/prod/js/vendors-app.a252b6908a42a5fa13e28badc33e76cc.js:22:14979)
```

**Comment by luisherranz** [comment]
Fixed in https://github.com/worona/starter-app-theme-worona/commit/1fbb3ed89bd7dcf0b3de95a067e8469d2645a33c
